package com.yourorg.parking.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Entity class representing a parking spot in the smart parking facility.
 * 
 * This class models a physical parking space within the facility. Each spot
 * is uniquely identified by its spot number and is designated for a specific
 * type of vehicle. The spot's status indicates its current availability.
 * 
 * The floor and zone attributes help organize the parking facility into
 * logical sections, making it easier for vehicles to find their assigned spots
 * and for the system to implement allocation strategies (e.g., nearest available spot).
 * 
 * Status values:
 * - AVAILABLE: Spot is empty and can be assigned
 * - OCCUPIED: Spot is currently in use
 * - RESERVED: Spot is reserved for future use
 * - MAINTENANCE: Spot is temporarily unavailable due to maintenance
 * 
 * @author Smart Parking System
 * @version 1.0
 */
@Entity
@Table(name = "parking_spots")
@Data
public class ParkingSpot {
    
    /**
     * Unique identifier for the parking spot in the database.
     * Auto-generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable spot identifier (e.g., "A1-101", "B2-205").
     * Must be unique across all spots and cannot be null.
     * This is displayed to users when they check in or need to find their vehicle.
     */
    @Column(unique = true, nullable = false)
    private String spotNumber;

    /**
     * Type of vehicle this spot is designated for.
     * Common values include: CAR, BIKE, TRUCK, etc.
     * Only vehicles matching this type can be allocated to this spot.
     * Cannot be null as it's essential for the allocation algorithm.
     */
    @Column(nullable = false)
    private String vehicleType;

    /**
     * Current status of the parking spot.
     * Valid values: AVAILABLE, OCCUPIED, RESERVED, MAINTENANCE
     * Cannot be null as the system needs to know spot availability at all times.
     */
    @Column(nullable = false)
    private String status;

    /**
     * Floor or level where this parking spot is located (e.g., "Ground", "1", "2", "B1").
     * Cannot be null as it's used for navigation and allocation strategies.
     */
    @Column(nullable = false)
    private String floor;

    /**
     * Zone or section within the floor (e.g., "A", "B", "North", "South").
     * Cannot be null as it helps organize the facility into logical sections.
     * Used in allocation strategies to minimize walking distance.
     */
    @Column(nullable = false)
    private String zone;
}





