package com.yourorg.parking.model;

import jakarta.persistence.*;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity class representing a parking transaction in the smart parking system.
 * 
 * This class models the complete lifecycle of a parking session, from check-in
 * to check-out. It tracks which vehicle is parked in which spot, the duration
 * of parking, and the fees charged.
 * 
 * A transaction is created when a vehicle checks in (status = ACTIVE) and is
 * completed when the vehicle checks out (status = COMPLETED). The system can
 * also cancel transactions if needed (status = CANCELLED).
 * 
 * The transaction links together three key pieces of information:
 * 1. The vehicle (through the vehicle foreign key)
 * 2. The assigned parking spot (through the spot foreign key)
 * 3. The time-based parking session details
 * 
 * Status values:
 * - ACTIVE: Vehicle is currently parked (checkOutTime is null)
 * - COMPLETED: Vehicle has checked out (checkOutTime is set, fee calculated)
 * - CANCELLED: Transaction was cancelled (e.g., due to error or special circumstances)
 * 
 * @author Smart Parking System
 * @version 1.0
 */
@Entity
@Table(name = "parking_transactions")
@Data
public class ParkingTransaction {
    
    /**
     * Unique identifier for the parking transaction in the database.
     * Auto-generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The vehicle associated with this parking transaction.
     * Many-to-one relationship: multiple transactions can be associated with one vehicle
     * (e.g., the same vehicle parking multiple times).
     * Cannot be null as every transaction must be linked to a vehicle.
     */
    @ManyToOne
    @JoinColumn(name = "vehicle_id", nullable = false)
    private Vehicle vehicle;

    /**
     * The parking spot assigned for this transaction.
     * Many-to-one relationship: multiple transactions can use the same spot
     * over time, but only one active transaction per spot at any given time.
     * Cannot be null as every transaction must be linked to a parking spot.
     */
    @ManyToOne
    @JoinColumn(name = "spot_id", nullable = false)
    private ParkingSpot parkingSpot;

    /**
     * Timestamp when the vehicle checked in and the transaction started.
     * Cannot be null as it's required to calculate parking duration and fees.
     * Set automatically when the transaction is created.
     */
    @Column(nullable = false)
    private LocalDateTime checkInTime;

    /**
     * Timestamp when the vehicle checked out and the transaction ended.
     * Null while the vehicle is still parked (transaction is ACTIVE).
     * Set when the vehicle checks out, triggering fee calculation.
     */
    private LocalDateTime checkOutTime;

    /**
     * Total parking fee charged for this transaction.
     * Calculated based on the duration (checkOutTime - checkInTime) and
     * the vehicle type's rate structure.
     * Null until check-out when the fee is calculated.
     */
    private BigDecimal totalFee;

    /**
     * Current status of the parking transaction.
     * Valid values: ACTIVE, COMPLETED, CANCELLED
     * Cannot be null as the system needs to track transaction state.
     * 
     * ACTIVE: Transaction is ongoing, vehicle is parked
     * COMPLETED: Transaction is finished, vehicle has checked out
     * CANCELLED: Transaction was cancelled (error, admin action, etc.)
     */
    @Column(nullable = false)
    private String status;
}





