package com.yourorg.parking.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Entity class representing a vehicle in the smart parking system.
 * 
 * This class stores information about vehicles that use the parking facility,
 * including their registration number, type, and owner details. Each vehicle
 * is uniquely identified by its vehicle number (license plate).
 * 
 * The vehicle type determines which parking spots the vehicle can be assigned to,
 * as different spots are designated for different vehicle types (e.g., CAR, BIKE, TRUCK).
 * 
 * @author Smart Parking System
 * @version 1.0
 */
@Entity
@Table(name = "vehicles")
@Data
public class Vehicle {
    
    /**
     * Unique identifier for the vehicle in the database.
     * Auto-generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Vehicle registration number (license plate).
     * Must be unique across all vehicles and cannot be null.
     * This serves as the primary business identifier for the vehicle.
     */
    @Column(unique = true, nullable = false)
    private String vehicleNumber;

    /**
     * Type of vehicle, determines which parking spots it can use.
     * Common values include: CAR, BIKE, TRUCK, SUV, etc.
     * Cannot be null as spot allocation depends on this field.
     */
    @Column(nullable = false)
    private String vehicleType;

    /**
     * Name of the vehicle owner.
     * Optional field for record-keeping and contact purposes.
     */
    private String ownerName;
    
    /**
     * Contact information for the vehicle owner (phone number, email, etc.).
     * Optional field used for notifications or emergencies.
     */
    private String ownerContact;
}





