-- H2-compatible schema for Smart Parking sample
-- Uses simpler types and CURRENT_TIMESTAMP

CREATE TABLE parking_spot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  floor INT NOT NULL,
  zone VARCHAR(64),
  spot_number VARCHAR(64),
  size VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE',
  sensor_id VARCHAR(128),
  metadata VARCHAR(1000),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  version INT NOT NULL DEFAULT 1
);

CREATE TABLE parking_ticket (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  spot_id BIGINT NOT NULL REFERENCES parking_spot(id),
  vehicle_reg VARCHAR(32) NOT NULL,
  vehicle_size VARCHAR(32) NOT NULL,
  entry_time TIMESTAMP NOT NULL,
  exit_time TIMESTAMP,
  fee DECIMAL(10, 2)
);
